title: Flexa Group Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.flexagroup.co.uk
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#D70040"
  systems:
    - name: Gateway
      category: Uncategorized
    - name: Backup Gateway
      category: Uncategorized
    - name: Website
      description: The web frontend for the application.
      category: Uncategorized
      link: https://example.com/
    - name: API
      description: The guts of the application.
      category: North Coast
    - name: Media Proxy
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Uncategorized
    - category: Uncategorized
      name: Careers System
    - name: Blogs System
      category: Uncategorized
    - name: Payments System
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#3d96d9"
  enableLastMod: true
  headerTextColor: black
  logo: /img/flexa_logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: Website
      link: https://flexagroup.co.uk
    - name: Discord
      link: https://discord.flexagroup.co.uk
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#FFC000"
  notice: "#1155cc"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Uncategorized
      description: The main servers are located here.
      closed: true
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
