title: Flexa Group Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.flexagroup.co.uk
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#D70040"
  systems:
    - name: Gateway
      category: Flexa Free Tier
    - name: Backup Gateway
      category: Flexa Free Tier
    - name: API
      category: Flexa Free Tier
    - name: Proxy Services
      category: Flexa Free Tier
    - name: Gateway
      category: Flexa Tech Mode
    - name: Flexa Tech Mode
      category: Backup Gateway
    - category: Flexa Tech Mode
      name: API
    - category: Flexa Tech Mode
      name: Proxy Services
    - name: Frontend
      category: Flexa Group Site
    - name: Backend
      category: Flexa Group Site
    - name: Careers System
      category: Flexa Group Site
    - category: Flexa Group Site
      name: Blogs System
    - category: Flexa Group Site
      name: Payment System
    - category: Support System
      name: Chat Support
    - name: Call Support
      category: Support System
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#3d96d9"
  enableLastMod: true
  headerTextColor: black
  logo: /img/flexa_logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: Website
      link: https://flexagroup.co.uk
    - name: Discord
      link: https://discord.flexagroup.co.uk
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#FFC000"
  notice: "#1155cc"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Flexa Free Tier
      untitled: false
    - name: Flexa Tech Mode
    - name: Flexa Group Site
    - name: Support System
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
